# Generated by Django 4.1.1 on 2022-09-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
