# Generated by Django 4.1.1 on 2022-09-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("is_in_stock", models.BooleanField(default=True)),
                ("slug", models.SlugField(blank=True, null=True)),
            ],
            options={"verbose_name": "Product", "verbose_name_plural": "Products",},
        ),
    ]
